### PR TITLE
src: Deduplicate read enable generation.

### PR DESCRIPTION
**Pull request by Blebowski**

### CODE REVIEW

**Comment by amykyta3** [comment]
I cannot accept this pull request. I attempted to run the unit tests on this change, and nearly all of them fail.
This implementation does not correctly handle any of the required scoping semantics.

**Comment by Blebowski** [comment]
Yup, it was only draft. I need to bring-up the questa free edition to get the tests running.

**Comment by amykyta3** [comment]
Again, as discussed in #103, I would really want to see evidence that this improves performance. Otherwise I do not have a compelling reason to accept PRs for issue #103 that add unnecessary complexity to the tool.

**Comment by Blebowski** [comment]
Understood.

**Pull request closed without merging**
